# Generated by Django 5.1.3 on 2024-12-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={},
        ),
        migrations.AlterModelManagers(
            name='cat',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cat',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='username',
        ),
        migrations.AlterField(
            model_name='mission',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.cat'),
        ),
    ]
